steps:
  - name: 'node'
    entrypoint: yarn
    args: ['--production']
    timeout: 200s
  - name: 'node'
    entrypoint: yarn
    args: ['build']
    env:
      - 'API_URL=${_API_URL}'
      - 'DEBUG=${_DEBUG}'
      - 'GA_PRODUCT=${_GA_PRODUCT}'
      - 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}'
      - 'SENTRY_DSN=${_SENTRY_DSN}'
      - 'SENTRY_ORG=${_SENTRY_ORG}'
      - 'SENTRY_PROJECT=${_SENTRY_PROJECT}'
      - 'SPEECH_TO_TEXT_JOB_TIMEOUT=${_SPEECH_TO_TEXT_JOB_TIMEOUT}'
    timeout: 500s
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ["-m", "rsync", "-r", "-c", "-d", './public', 'gs://${_STATIC_ASSET_BUCKET}']